query AdminSession {
    admin {
        session {
            ...AdminSessionFields
        }
    }
}

query AdminAccountsScreen($cursor: String, $limit: Int) {
    admin {
        adminAccounts(cursor: $cursor, limit: $limit) {
            nodes {
                ...AdminAccountListFields
            }
            pageInfo {
                hasMore
                nextCursor
            }
        }
    }
}

fragment AdminAccountListFields on AdminAccount {
    id
    username
    acct
    createdAt
}

fragment AdminSessionFields on AdminSession {
    loggedIn
    passwordConfigured
}

mutation AdminLogin($password: String!) {
    admin {
        login(password: $password) {
            session {
                ...AdminSessionFields
            }
            failure
        }
    }
}

mutation AdminLogout {
    admin {
        logout {
            ...AdminSessionFields
        }
    }
}

mutation AdminAddUser($query: AddUserQuery!) {
    admin {
        addUser(query: $query) {
            adminAccount {
                ...AdminAccountListFields
            }
            failure {
                unusableCharacters
                maxLength
                minLength
                isDuplicated
                passwordMinLength
            }
        }
    }
}
